spring:
  application:
    name: user-api

server:
  port: ${PORT:8000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost