spring:
  application:
    name: payroll-api
server:
  port: ${PORT:8100}
eureka:
  client:
    service-url:
      default-zone: ${eureka_url:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost